apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.env.name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: {{ .Values.cluster.name }}
  server: {{ .Values.cluster.host }}
  namespaces: {{ .Values.env.namespace }}
  config: |
    {
      "bearerToken": "{{ .Values.env.token }}",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "{{ .Values.env.ca }}"
      }
    }
