apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: krush-manager-role-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "env-init.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: krush-manager-role
