apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: krush-manager-role
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'